[package]
name = "orb-relay-client"
version = "0.1.0"
edition.workspace = true
publish = false

[dependencies]
clap = { version = "4", features = ["derive"] }
eyre.workspace = true
flexi_logger.workspace = true
json5 = "0.4"
orb-relay-messages.workspace = true
orb-security-utils.workspace = true
rand = "0.8"
serde_json.workspace = true
sha2 = "0.10"
tokio-stream.workspace = true
tokio-util.workspace = true
tokio.workspace = true
tracing-subscriber = "0.3"
tracing.workspace = true
