[package]
name = "update-agent-loader"
version = "0.0.1"
description = "A loader for the update-agent"
publish = false

edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[features]
default = []
# The allow_http feature enables HTTP URLs for testing purposes
# This feature cannot be enabled in release mode due to a compile-time check
allow_http = []

[dependencies]
reqwest = { version = "0.11.4", features = ["blocking", "rustls-tls-native-roots"], default-features = false }
eyre = "0.6.9"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
env_logger = "0.10.1"
thiserror = "1.0.57"
url = "2.2.2"
nix = { version = "0.26", features = ["mman", "process"] }
clap = { version = "4.4", features = ["derive"] }
ed25519-dalek = "2.1.1"
base64 = "0.22.1"
lazy_static = "1.5.0"

[dev-dependencies]
wiremock = "0.5.19"
tokio = { version = "1.29", features = ["full"] }
tempfile = "3.8.0"
escargot = "0.5.13"
rand = "0.8"

[build-dependencies]
rand = "0.8.5"
ed25519-dalek = "2.1.1"
base64 = "0.22.1"
