[toolchain]
channel = "1.81.0" # See Cargo.toml
targets = ["aarch64-unknown-linux-gnu", "x86_64-unknown-linux-gnu"]
profile = "minimal"
components = ["clippy", "llvm-tools-preview", "rustfmt", "rust-src", "rust-analyzer"]
