[package]
name = "orb-mcu-schema"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prost = "0.10.4"

[build-dependencies]
prost-build = "0.10.4"
