[package]
name = "orb-secure-storage-ta"
version = "0.0.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
optee-utee-sys.workspace = true
optee-utee.workspace = true
orb-secure-storage-proto.path = "../proto"
serde_json = { workspace = true, default-features = false, features = ["alloc"] }
thiserror = { workspace = true, default-features = false }
uuid = { workspace = true, features = ["v5"] }

[build-dependencies]
optee-utee-build = "0.7.0"
orb-secure-storage-proto.path = "../proto"

[package.metadata.orb-optee]
uuid_path = "../uuid.txt"
