[package]
name = "orb-secure-storage-ta"
version = "0.0.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
optee-utee.workspace = true
optee-utee-sys.workspace = true
orb-secure-storage-proto.path = "../proto"
thiserror.workspace = true
uuid.workspace = true
anyhow.workspace = true

[build-dependencies]
optee-utee-build = "0.7.0"
orb-secure-storage-proto.path = "../proto"

[package.metadata.orb-optee]
uuid_path = "../uuid.txt"
