[package]
name = "orb-secure-storage-ta"
version = "0.0.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
optee-utee.workspace = true
orb-secure-storage-proto.path = "../proto"
optee-utee-sys.workspace = true

[build-dependencies]
optee-utee-build = "0.7.0"
orb-secure-storage-proto.path = "../proto"
