[package]
name = "orb-wt-video"
version = "0.0.0"
description = "WebTransport based video streamer"

edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
axum = "0.8.1"
axum-extra = "0.10.0"
axum-server = { version = "0.7.1", features = ["tls-rustls-no-provider"] }
base64.workspace = true
bon.workspace = true
clap = { workspace = true, features = ["derive"] }
color-eyre.workspace = true
derive_more = { workspace = true, features = ["into", "as_ref", "deref"] }
futures.workspace = true
keycode = { version = "0.4.0", features = ["serde"] }
orb-telemetry.workspace = true
png = "0.17.16"
rcgen = "0.13.2"
serde = { workspace = true, features = ["derive"] }
tokio = { workspace = true, features = ["full"] }
tokio-serde = { version = "0.9.0", features = ["json"] }
tokio-util = { workspace = true, features = ["codec"] }
tower = "0.5.2"
tower-http = { version = "0.6.2", features = ["fs"] }
tracing.workspace = true
wtransport = "0.6.1"
