[package]
name = "test-utils"
version = "0.1.0"
authors = ["Victor Menge <vmenge@users.noreply.github.com>"]

edition.workspace = true
repository.workspace = true
license.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
nix = { workspace = true, features = ["socket"] }
tempfile.workspace = true
testcontainers.workspace = true
tokio = { workspace = true, features = ["full"] }
