[package]
name = "orb-telemetry"
version = "0.0.0"
description = "Standardized telemetry setup for the orb"
authors = ["Ryan Butler <thebutlah@users.noreply.github.com>"]
publish = false

edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[features]
default = ["otel"]
otel = [
	"dep:opentelemetry",
	"dep:opentelemetry-otlp",
	"dep:opentelemetry_sdk",
	"dep:tracing-opentelemetry",
	"dep:tokio",
]
zbus-tracing = ["dep:zbus"]

[dependencies]
opentelemetry = { version = "0.27", features = ["trace"], optional = true }
opentelemetry-otlp = { version = "0.27", features = [
	"trace",
	"grpc-tonic",
], optional = true }
opentelemetry_sdk = { version = "0.27", features = ["rt-tokio"], optional = true }
thiserror = { workspace = true, features = ["std"] }
tokio = { workspace = true, optional = true }
tracing.workspace = true
tracing-journald.workspace = true
tracing-opentelemetry = { workspace = true, optional = true }
tracing-subscriber = { workspace = true, features = ["registry", "env-filter"] }
zbus = { workspace = true, optional = true }

[dev-dependencies]
color-eyre.workspace = true

[target.'cfg(tokio_unstable)'.dependencies]
console-subscriber.workspace = true

[lints.rust.unexpected_cfgs]
check-cfg = ['cfg(tokio_unstable)']
level = "warn"
