[package]
name = "orb-secure-storage-ca"
version = "0.0.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
optee-teec.workspace = true
orb-secure-storage-proto.path = "../proto"
rustix = { workspace = true, features = ["process"] }

[package.metadata.orb]
unsupported_targets = [
	"aarch64-apple-darwin",
	"x86_64-apple-darwin",
	"x86_64-unknown-linux-gnu",
]
