[package]
name = "orb-secure-storage-ca"
version = "0.0.0"
description = "CLI to talk to the orb-secure-storage TA"
authors = ["Ryan Butler <thebutlah@users.noreply.github.com>"]
publish = false

edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
clap-stdin.workspace = true
clap.workspace = true
color-eyre.workspace = true
eyre.workspace = true
optee-teec.workspace = true
orb-secure-storage-proto.path = "../proto"
orb-telemetry.workspace = true
rand.workspace = true
rustix = { workspace = true, features = ["process"] }
serde.workspace = true
serde_json.workspace = true
tracing-subscriber.workspace = true
tracing.workspace = true

[package.metadata.orb]
unsupported_targets = [
	"aarch64-apple-darwin",
	"x86_64-apple-darwin",
	"x86_64-unknown-linux-gnu",
]

[package.metadata.deb]
assets = [["target/release/orb-secure-storage-ca", "/usr/local/bin/", "755"]]
