[package]
name = "orb-update-agent-core"
version = "0.0.0"
authors = ["Richard Janis Goldschmidt", "Galileo Daras <galileo@getcoffee.io>"]
description = "Systemd server that downloads and installs OTA updates"
publish = false

edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[features]
# If provided, we skip manifest signature verification
skip-manifest-signature-verification = []

[dependencies]
base64.workspace = true
dogstatsd = "0.11.1"
ed25519-dalek.workspace = true
gpt.workspace = true
hex-literal.workspace = true
jose-jwk = { workspace = true, default-features = false }
once_cell = "1.18.0"
orb-slot-ctrl.workspace = true
rustix = { workspace = true, features = ["fs"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true, features = ["raw_value"] }
sha2.workspace = true
tap = "1.0.1"
thiserror = { workspace = true, features = ["std"] }
tracing.workspace = true
url = { version = "2.2.2", features = ["serde"] }
