[build]
# uncomment to use tokio console
# rustflags = ["--cfg", "tokio_unstable"]

[net]
# libgit2 doesn't handle git credentials well
git-fetch-with-cli = true

# Run cargo with `RUSTFLAGS='--cfg docker_runner'`
[target.'cfg(docker_runner)']
runner = "docker/cargo-runner.sh"
# Run cargo with `RUSTFLAGS='--cfg nix_docker_runner'`
[target.'cfg(nix_docker_runner)']
runner = "docker/nix-cargo-runner.sh"

[target.x86_64-unknown-linux-gnu]
rustflags = ["-Clinker-features=-lld"] # dont use lld, it has issues with fenix rn

[alias]
x = "run -q --package x --"
