[package]
name = "orb-info"
version = "0.0.0"
description = "Common orb info functionality"
authors = ["Paul Quinn <paulquinn00@users.noreply.github.com>"]
publish = false

edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[features]
default = ["orb-id", "orb-jabil-id", "orb-name", "orb-token", "async"]
async = ["dep:tokio", "dep:tokio-util"]
orb-id = []
orb-name = []
orb-jabil-id = []
orb-token = ["dep:zbus", "dep:tokio", "dep:tokio-util"]

[dependencies]
color-eyre.workspace = true
futures-lite = "2.6.0"
hex = "0.4.3"
http.workspace = true
notify = "8.0.0"
orb-attest-dbus.workspace = true
tokio = { workspace = true, optional = true }
tokio-util = { workspace = true, optional = true }
tracing.workspace = true
thiserror.workspace = true
zbus = { workspace = true, optional = true }

[dev-dependencies]
serial_test = "3.2.0"
tokio.workspace = true
