[package]
name = "orb-update-agent"
version = "6.0.4"
authors = ["Richard Janis Goldschmidt", "Galileo Daras <galileo@getcoffee.io>"]
description = "Systemd service that downloads and installs OTA updates"
publish = false

edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[features]
can-update-test = []
# If provided, we skip manifest signature verification
skip-manifest-signature-verification = [
	"orb-update-agent-core/skip-manifest-signature-verification",
]

[dependencies]
bipatch = "1.0.0"
bon.workspace = true
bytes.workspace = true
clap = { workspace = true, features = ["derive"] }
const_format = "0.2.30"
crc32fast = "1.3"
eyre.workspace = true
figment = { version = "0.10.8", features = ["env", "toml"] }
flume.workspace = true
gpt.workspace = true
hex.workspace = true
jod-thread = "0.1.2"
libc.workspace = true
nix = { workspace = true, default-features = false, features = ["fs"] }
once_cell = "1.17.0"
orb-build-info.workspace = true
orb-io-utils.workspace = true
orb-telemetry.workspace = true
orb-update-agent-core.workspace = true
orb-update-agent-dbus.workspace = true
orb-zbus-proxies = { workspace = true, features = ["login1"] }
polling = "2.2.0"
ruzstd = "0.8.0"
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
serde_path_to_error = "0.1.8"
serde_with = "3.6.1"
sha2.workspace = true
tap = "1.0.1"
tempfile = "3.8.0"
thiserror = { workspace = true, features = ["std"] }
tracing.workspace = true
url = "2.2.2"
xz2 = "0.1.6"
zbus.workspace = true
efivar.workspace = true
orb-slot-ctrl.workspace = true
orb-info = { workspace = true, features = ["orb-os-release"] }

[dependencies.can-rs]
workspace = true
features = ["isotp"]

[dependencies.reqwest]
version = "0.11.4"
features = ["blocking", "json", "multipart", "rustls-tls-native-roots"]
default-features = false

[dependencies.orb-messages]
git = "https://github.com/worldcoin/orb-messages"
# Points to a commit not on main. See https://github.com/worldcoin/orb-messages/pull/37
rev = "c439077c7c1bc3a8eb6f224c32b5b4d60d094809"

[dev-dependencies]
figment = { version = "0.10.8", features = ["test"] }
cmd_lib.workspace = true
toml = "0.8.10"

[build-dependencies]
orb-build-info = { workspace = true, features = ["build-script"] }

[package.metadata.orb]
unsupported_targets = ["aarch64-apple-darwin", "x86_64-apple-darwin"]
flavors = [{ name = "no-sig", features = ["skip-manifest-signature-verification"] }]

[package.metadata.deb]
maintainer-scripts = "debian/"
assets = [["target/release/orb-update-agent", "/usr/local/bin/", "755"]]
systemd-units = [{ unit-name = "worldcoin-update-agent" }]
