[package]
name = "orb-qr-link"
version = "0.1.0"
description = "Data link between Worldcoin App and Orb through QR-codes"
authors = ["Valentyn Valiaiev <valentyn.valiaiev@toolsforhumanity.com>"]
publish = false

# orb-core can't consume crates that use workspace inheritance :(
edition = "2021"
license = "MIT OR (Apache-2.0 WITH LLVM-exception)"
repository = "https://github.com/worldcoin/orb-software"
rust-version = "1.77.0"

[features]
decode = []
default = ["encode", "decode"]
encode = []

[dependencies]
blake3 = "1.5.0"
data-encoding = "2.4.0"
serde = { version = "1.0.188", features = ["derive"] }
thiserror = "1.0.57"
uuid = { version = "1.4.1", features = ["v4"] }

[dependencies.orb-relay-messages]
features = ["client"]
git = "https://github.com/worldcoin/orb-relay-messages.git"
rev = "2cfc4ab1d15acef3a876ef268d5cfe2a5a57b3b3"

[[test]]
name = "verification"
required-features = ["encode", "decode"]
