[package]
name = "orb-relay-client"
version = "0.1.0"
publish = false
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

# orb-core can't consume crates that use workspace inheritance :(
edition = "2021"
license = "MIT OR (Apache-2.0 WITH LLVM-exception)"
repository = "https://github.com/worldcoin/orb-software"
rust-version = "1.82.0"

[dependencies]
clap = { version = "4", features = ["derive", "env"] }
derive_more = { workspace = true, features = ["deref", "from", "into"] }
eyre.workspace = true
orb-endpoints.workspace = true
orb-relay-messages.workspace = true
orb-security-utils = { workspace = true, features = ["reqwest"] }
orb-telemetry.workspace = true
rand = "0.8"
serde_json.workspace = true
secrecy.workspace = true
sha2 = "0.10"
tokio-stream.workspace = true
tokio-util.workspace = true
tokio.workspace = true
tracing-subscriber.workspace = true
tracing.workspace = true
