[package]
name = "orb-speed-test"
version = "0.0.0"
authors = ["Popov Philipp <filipp.popov@toolsforhumanity.com>"]
description = "Network speed test utility for Orb"
publish = false

edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lib]
name = "orb_speed_test"
path = "src/lib.rs"

[[bin]]
name = "orb-speed-test"
path = "src/main.rs"

[dependencies]
base64.workspace = true
clap = { workspace = true, features = ["derive"] }
color-eyre.workspace = true
flate2.workspace = true
orb-attest-dbus.path = "../attest/dbus"
orb-build-info.workspace = true
orb-info.path = "../orb-info"
rand.workspace = true
reqwest = { workspace = true, features = ["multipart", "stream", "json"] }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
sha2.workspace = true
tar.workspace = true
tokio = { workspace = true, features = ["macros", "rt"] }
uuid = { workspace = true, features = ["v4"] }
zbus.workspace = true

[build-dependencies]
orb-build-info = { workspace = true, features = ["build-script"] }

[package.metadata.deb]
assets = [["target/release/orb-speed-test", "/usr/local/bin/", "755"]]
