[package]
name = "orb-ui"
version = "0.0.3"
description = "Systemd daemon responsible for running the UI on the orb."
authors = ["Cyril Fougeray <cyril.fougeray@toolsforhumanity.com>"]
publish = false

edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
async-trait = "0.1.74"
clap.workspace = true
color-eyre.workspace = true
dashmap = "5.5.3"
derive_more.workspace = true
eyre.workspace = true
futures.workspace = true
hound = "3.5.1"
humantime = "2.1.0"
orb-build-info.path = "../build-info"
orb-info = { workspace = true, features = ["orb-os-release"], default-features = false }
orb-messages.workspace = true
orb-rgb.path = "rgb"
orb-sound.path = "sound"
orb-telemetry.workspace = true
orb-uart.path = "uart"
pid.path = "pid"
prost = "0.12.3"
rand = "0.8.5"
serde_json = "1.0.108"
serde.workspace = true
thiserror = { workspace = true, features = ["std"] }
tokio-stream = "0.1.14"
tokio.workspace = true
tracing.workspace = true
zbus.workspace = true

[build-dependencies]
orb-build-info = { path = "../build-info", features = ["build-script"] }

[[example]]
name = "ui-replay"
path = "examples/ui-replay.rs"

# dependencies for the dbus-client example
[dev-dependencies]
chrono = "0.4.35"
hound = "3.5.1"

[package.metadata.deb]
maintainer-scripts = "debian/"
assets = [
	[
		"sound/assets/*.wav",
		"/home/worldcoin/data/sounds/",
		"644",
	],
	[
		"target/release/orb-ui",
		"/usr/local/bin/",
		"755",
	],
]
systemd-units = [{ unit-name = "worldcoin-ui" }]

[package.metadata.orb]
unsupported_targets = ["aarch64-apple-darwin", "x86_64-apple-darwin"]

[lints.rust.unexpected_cfgs]
check-cfg = ['cfg(tokio_unstable)']
level = "warn"
