[package]
name = "orb-jobs-agent"
version = "0.0.0"
authors = ["Paul Quinn <paulquinn00@users.noreply.github.com>"]
description = "Worldcoin Jobs Agent"
publish = false

edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
async-trait.workspace = true
bon.workspace = true
clap = { workspace = true, features = ["derive", "env"] }
color-eyre.workspace = true
const_format = "0.2.30"
chrono.workspace = true
dashmap.workspace = true
figment = { version = "0.10.8", features = ["env", "toml"] }
futures.workspace = true
libc.workspace = true
listenfd = "1.0.0"
once_cell = "1.15.0"
orb-build-info.workspace = true
orb-endpoints.workspace = true
orb-info = { workspace = true, features = [
	"orb-id",
	"orb-name",
	"orb-jabil-id",
	"orb-token",
	"async",
	"orb-os-release",
] }
orb-zbus-proxies = { workspace = true, features = ["login1"] }
orb-telemetry.workspace = true
rustls.workspace = true
secrecy = { workspace = true, features = ["serde"] }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
serde_path_to_error = "0.1.8"
serde_with = "3.11.0"
tap = "1.0.1"
thiserror = { workspace = true, features = ["std"] }
tokio = { workspace = true, features = ["macros", "net", "rt-multi-thread", "io-util"] }
tokio-stream.workspace = true
tokio-test.workspace = true
tokio-util.workspace = true
tracing = { workspace = true, features = ["attributes"] }
zbus = { workspace = true, default-features = false, features = ["tokio"] }
zbus_systemd = { workspace = true, features = ["systemd1", "login1"] }
orb-connd-dbus.workspace = true

[dependencies.orb-relay-client]
git = "https://github.com/worldcoin/orb-relay-messages.git"
rev = "301889d17fa0c283bdbad8eb2f5659ee5effb40f"

[dependencies.orb-relay-messages]
git = "https://github.com/worldcoin/orb-relay-messages.git"
rev = "301889d17fa0c283bdbad8eb2f5659ee5effb40f"
features = ["client"]

[dependencies.orb-relay-test-utils]
git = "https://github.com/worldcoin/orb-relay-messages.git"
rev = "301889d17fa0c283bdbad8eb2f5659ee5effb40f"

[build-dependencies]
orb-build-info = { workspace = true, features = ["build-script"] }

[dev-dependencies]
async-tempfile.workspace = true
dbus-launch = "0.2.0"
flume.workspace = true
serial_test = "3.2.0"
test-utils.workspace = true
test-with.workspace = true
testcontainers.workspace = true
tokio = { workspace = true, features = ["sync", "test-util"] }
uuid = { version = "1.17.0", features = ["v4"] }
mockall.workspace = true

[package.metadata.deb]
maintainer-scripts = "debian/"
assets = [["target/release/orb-jobs-agent", "/usr/local/bin/", "755"]]
systemd-units = [{ unit-name = "worldcoin-jobs-agent" }]
